export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

import HomeNavbar from "../../components/homeNavbar";

export default function HomeLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <HomeNavbar />
      {children}
    </>
  );
}
